spring.application.name=api
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:noscam}
spring.datasource.username=${POSTGRES_USER:noscam}
spring.datasource.password=${POSTGRES_PASSWORD:noscam}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
