CREATE TABLE risk_settings
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT                   NOT NULL UNIQUE,
    alert_threshold  INTEGER                  NOT NULL,
    low_max          INTEGER                  NOT NULL,
    medium_max       INTEGER                  NOT NULL,
    config_version   INTEGER                  NOT NULL,
    engine_version   INTEGER                  NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_risk_settings_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_risk_settings_threshold CHECK (alert_threshold BETWEEN 0 AND 100),
    CONSTRAINT chk_risk_settings_low_max CHECK (low_max BETWEEN 0 AND 100),
    CONSTRAINT chk_risk_settings_medium_max CHECK (medium_max BETWEEN 0 AND 100),
    CONSTRAINT chk_risk_settings_boundaries CHECK (low_max < medium_max)
);

CREATE TABLE risk_factor_configs
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settings_id    BIGINT                   NOT NULL,
    factor_key     VARCHAR(64)              NOT NULL,
    enabled        BOOLEAN                  NOT NULL,
    max_points     INTEGER                  NOT NULL,
    parameters     JSONB                    NOT NULL DEFAULT '{}'::jsonb,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_risk_factor_configs_settings FOREIGN KEY (settings_id) REFERENCES risk_settings (id) ON DELETE CASCADE,
    CONSTRAINT uk_risk_factor_configs_settings_key UNIQUE (settings_id, factor_key),
    CONSTRAINT chk_risk_factor_configs_max_points CHECK (max_points >= 0)
);

CREATE TABLE risk_assessments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id          UUID                     NOT NULL UNIQUE,
    transaction_id     BIGINT                   NOT NULL,
    user_id            BIGINT                   NOT NULL,
    score              INTEGER                  NOT NULL,
    risk_level         VARCHAR(16)              NOT NULL,
    primary_reason     TEXT                     NOT NULL,
    engine_version     INTEGER                  NOT NULL,
    config_version     INTEGER                  NOT NULL,
    config_snapshot    JSONB                    NOT NULL,
    content_hash       VARCHAR(64)              NOT NULL,
    scored_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_risk_assessments_transactions FOREIGN KEY (transaction_id) REFERENCES transactions (id),
    CONSTRAINT fk_risk_assessments_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_risk_assessments_transaction_hash UNIQUE (transaction_id, content_hash),
    CONSTRAINT chk_risk_assessments_score CHECK (score BETWEEN 0 AND 100)
);

CREATE INDEX idx_risk_assessments_transaction_scored
    ON risk_assessments (transaction_id, scored_at DESC);

CREATE TABLE risk_factor_results
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id   BIGINT        NOT NULL,
    factor_key      VARCHAR(64)   NOT NULL,
    points          INTEGER       NOT NULL,
    matched         BOOLEAN       NOT NULL,
    explanation     TEXT          NOT NULL,
    evidence        JSONB         NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT fk_risk_factor_results_assessments FOREIGN KEY (assessment_id) REFERENCES risk_assessments (id) ON DELETE CASCADE,
    CONSTRAINT uk_risk_factor_results_assessment_key UNIQUE (assessment_id, factor_key)
);
