CREATE TABLE notifications
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID                     NOT NULL UNIQUE,
    user_id         BIGINT                   NOT NULL,
    transaction_id  BIGINT                   NOT NULL,
    assessment_id   BIGINT                   NOT NULL,
    type            VARCHAR(32)              NOT NULL,
    title           VARCHAR(255)             NOT NULL,
    body            TEXT                     NOT NULL,
    score           INTEGER                  NOT NULL,
    read_at         TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_notifications_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_notifications_transactions FOREIGN KEY (transaction_id) REFERENCES transactions (id),
    CONSTRAINT fk_notifications_assessments FOREIGN KEY (assessment_id) REFERENCES risk_assessments (id),
    CONSTRAINT uk_notifications_txn_assessment_type UNIQUE (transaction_id, assessment_id, type)
);

CREATE INDEX idx_notifications_user_created ON notifications (user_id, created_at DESC);
CREATE INDEX idx_notifications_user_unread ON notifications (user_id, created_at DESC) WHERE read_at IS NULL;

CREATE TABLE plaid_webhook_events
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        UUID                     NOT NULL UNIQUE,
    provider_event_id VARCHAR(255),
    dedupe_hash      VARCHAR(64)              NOT NULL UNIQUE,
    plaid_item_id    BIGINT,
    webhook_type     VARCHAR(64)              NOT NULL,
    webhook_code     VARCHAR(64)              NOT NULL,
    payload          JSONB                    NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_plaid_webhook_events_items FOREIGN KEY (plaid_item_id) REFERENCES plaid_items (id)
);

CREATE TABLE sync_jobs
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        UUID                     NOT NULL UNIQUE,
    user_id          BIGINT                   NOT NULL,
    plaid_item_id    BIGINT,
    job_type         VARCHAR(64)              NOT NULL,
    state            VARCHAR(32)              NOT NULL,
    attempt_count    INTEGER                  NOT NULL DEFAULT 0,
    max_attempts     INTEGER                  NOT NULL DEFAULT 8,
    next_attempt_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    last_error       TEXT,
    payload          JSONB                    NOT NULL DEFAULT '{}'::jsonb,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sync_jobs_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_sync_jobs_plaid_items FOREIGN KEY (plaid_item_id) REFERENCES plaid_items (id)
);

CREATE INDEX idx_sync_jobs_claim
    ON sync_jobs (state, next_attempt_at);
CREATE INDEX idx_sync_jobs_user ON sync_jobs (user_id, created_at DESC);
