CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    email VARCHAR(254) NOT NULL UNIQUE,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

ALTER TABLE accounts
    ADD COLUMN user_id BIGINT NOT NULL,
    ADD CONSTRAINT fk_accounts_users
        FOREIGN KEY (user_id) REFERENCES users(id);

CREATE INDEX idx_accounts_user_id ON accounts(user_id);
