CREATE TABLE transactions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    public_id     UUID                        NOT NULL UNIQUE,
    account_id    BIGINT                      NOT NULL,
    user_id       BIGINT                      NOT NULL,
    source_type   VARCHAR(255)                NOT NULL,
    external_id   VARCHAR(255)                NOT NULL,
    amount        DECIMAL(19, 4)              NOT NULL,
    currency_code VARCHAR(3)                  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_transactions_accounts FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT fk_transactions_users FOREIGN KEY (user_id) REFERENCES users (id)
)