CREATE TABLE idempotency_records
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key  VARCHAR(255)             NOT NULL,
    user_id          BIGINT                   NOT NULL,
    endpoint         VARCHAR(255)             NOT NULL,
    request_hash     VARCHAR(64)              NOT NULL,
    request_status   VARCHAR(32)              NOT NULL,
    http_method      VARCHAR(10)              NOT NULL,
    response_code    INTEGER,
    response_body    JSONB,
    response_headers JSONB,
    lock_expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_idempotency_user_method_endpoint_key UNIQUE (user_id, http_method, endpoint, idempotency_key),
    CONSTRAINT chk_response_code
        CHECK (response_code IS NULL OR response_code BETWEEN 100 AND 599)
);

CREATE INDEX idx_idempotency_expiration
    ON idempotency_records (expires_at);