CREATE TABLE plaid_items
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID                     NOT NULL UNIQUE,
    user_id             BIGINT                   NOT NULL,
    plaid_item_id       VARCHAR(128)             NOT NULL,
    access_token        TEXT                     NOT NULL,
    institution_id      VARCHAR(64),
    institution_name    VARCHAR(255),
    cursor              TEXT,
    status              VARCHAR(32)              NOT NULL,
    consent_expires_at  TIMESTAMP WITH TIME ZONE,
    connected_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    last_successful_sync TIMESTAMP WITH TIME ZONE,
    last_error_code     VARCHAR(128),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_plaid_items_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_plaid_items_plaid_item_id UNIQUE (plaid_item_id)
);

CREATE INDEX idx_plaid_items_user_id ON plaid_items (user_id);

ALTER TABLE accounts
    ADD COLUMN plaid_item_id BIGINT,
    ADD COLUMN provider_account_id VARCHAR(128),
    ADD COLUMN mask VARCHAR(16),
    ADD COLUMN source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    ADD COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    ADD CONSTRAINT fk_accounts_plaid_items FOREIGN KEY (plaid_item_id) REFERENCES plaid_items (id);

CREATE UNIQUE INDEX uk_accounts_provider_identity
    ON accounts (plaid_item_id, provider_account_id)
    WHERE plaid_item_id IS NOT NULL AND provider_account_id IS NOT NULL;
